Repository Pjaijai/Referalah, pull requests merged in 2023-11, with the labels that each got.

#193 Feature/create post history page
  client/app/post/history/[userUuid]/page.tsx
  client/components/customized-ui/cards/referral-post.tsx
  client/components/customized-ui/info-display/created-at.tsx
  client/components/customized-ui/skeletons/card-list.tsx
  client/components/customized-ui/skeletons/card.tsx
  client/hooks/api/post/list-post-by-user-uuid.tsx
  client/modules/post/components/info-display/header.tsx
  client/modules/post/history/components/cards/post-history.tsx
  client/modules/post/history/template.tsx
  client/modules/post/referer/template.tsx
  client/modules/referral/referee/template.tsx
  client/modules/referral/referer/template.tsx
  client/types/api/response/referer-post.ts
  client/types/common/post.ts
  client/types/common/query-key-string.ts
  client/utils/common/api/index.tsx
  client/utils/common/helpers/format/created-at.ts
  client/utils/common/helpers/format/date.ts
Labels: feature

#195 Fix doc
  DEVELOPER.md
Labels: documentation

#202 BugFix/ Fix margin
  client/modules/profile/edit/template.tsx
  client/modules/profile/view/template.tsx
Labels: feature

#198 Feature/updating contact through post api
  supabase/.env.template
  supabase/functions/contact-through-post/index.ts
Labels: feature

#192 Feature/progressive web app
  client/.eslintrc.json
  client/.gitignore
  client/_document.js
  client/app/layout.tsx
  client/modules/post/referer/template.tsx
  client/modules/referral/referee/template.tsx
  client/modules/referral/referer/template.tsx
  client/next.config.mjs
  client/package.json
  client/public/Referalah-192.png
  client/public/Referalah-256.png
  client/public/Referalah-512.png
  client/public/manifest.json
  client/public/next.svg
  client/public/thirteen.svg
  client/public/vercel.svg
  client/yarn.lock
Labels: feature, help wanted

#206 Feature/adding site name to edit post page
  client/app/post/edit/[postUuid]/page.tsx
  client/config/site.ts
  client/modules/post/validation/edit.ts
Labels: feature

#212 Feature/seo optimization
  client/app/about/page.tsx
  client/app/auth/page.tsx
  client/app/contributors/page.tsx
  client/app/layout.tsx
  client/app/post/create/page.tsx
  client/app/post/referer/page.tsx
  client/app/privacy-policy/page.tsx
  client/app/profile/[userUuid]/page.tsx
  client/app/referee/page.tsx
  client/app/referer/page.tsx
  client/app/terms-and-conditions/page.tsx
  client/components/customized-ui/footer/nav.tsx
  client/components/site-header.tsx
  client/components/ui/separator.tsx
  client/config/site.ts
  client/modules/contributors/data/contributors.ts
  client/modules/profile/template.tsx
  client/modules/referral/referee/template.tsx
  client/modules/referral/referer/template.tsx
Labels: feature

#200 Refactor/post
  client/app/about/page.tsx
  client/app/auth/page.tsx
  client/app/contributors/page.tsx
  client/app/post/create/page.tsx
  client/app/post/history/[userUuid]/page.tsx
  client/app/privacy-policy/page.tsx
  client/app/profile/[userUuid]/page.tsx
  client/app/referee/page.tsx
  client/app/terms-and-conditions/page.tsx
  client/components/customized-ui/buttons/contact.tsx
  client/components/customized-ui/cards/profile.tsx
  client/components/customized-ui/cards/referral-post.tsx
  client/components/customized-ui/cards/referral.tsx
  client/components/customized-ui/info-display/created-at.tsx
  client/components/icons.tsx
  client/components/ui/button.tsx
  client/components/ui/separator.tsx
  client/modules/contributors/data/contributors.ts
  client/modules/post/components/info-display/card-info.tsx
  client/modules/post/components/info-display/details-info.tsx
  client/modules/post/components/info-display/header.tsx
  client/modules/post/history/components/cards/post-history.tsx
  client/modules/post/history/template.tsx
  client/modules/post/view/template.tsx
  client/modules/profile/template.tsx
  client/modules/referral/components/dialog/contact.tsx
  client/modules/referral/referee/template.tsx
  client/modules/referral/referer/template.tsx
  client/utils/common/helpers/format/created-at.ts
Labels: refactoring

#215 Feature/post history page button in profile page
  client/app/page.tsx
  client/app/post/history/[userUuid]/page.tsx
  client/components/icons.tsx
  client/config/site.ts
  client/modules/post/history/template.tsx
  client/modules/profile/view/template.tsx
  client/utils/common/api/index.tsx
Labels: feature

#216 Feature/block sending email if post is closed
  client/modules/post/view/template.tsx
  supabase/functions/_shared/types/post/status.ts
  supabase/functions/contact-through-post/index.ts
Labels: feature

#199 Feature/Adding user profile url to email template
  supabase/functions/contact-referral/index.ts
  supabase/functions/contact-through-post/index.ts
Labels: feature

#225 Feature/Fix search text
  client/modules/post/referee/template.tsx
  client/modules/post/referer/template.tsx
  client/modules/referral/referee/template.tsx
  client/modules/referral/referer/template.tsx
Labels: feature

#222 Feature/adding space in nav
  client/components/site-header.tsx
Labels: feature

#230 Feature/redirect to post detail page after creating
  client/modules/post/create/template.tsx
  client/utils/common/api/index.tsx
Labels: feature

#236 Feature/Adding AI warning text
  client/modules/referral/components/dialog/contact.tsx
Labels: feature, P1

#233 Doc/update sql script for create user in local
  DEVELOPER.md
  client/.env.template
Labels: documentation

#247 Feature/Created authenticated wrapper
  client/app/post/create/page.tsx
  client/components/wrappers/authenticated.tsx
Labels: feature

#254 Refactor/refactor types naming convention
  .gitignore
  client/app/post/create/page.tsx
  client/components/customized-ui/buttons/contact.tsx
  client/components/customized-ui/cards/referral.tsx
  client/components/customized-ui/pop-overs/search.tsx
  client/components/layouts/authenticated.tsx
  client/components/main-nav.tsx
  client/hooks/api/industry/get-Industry-list.tsx
  client/hooks/api/location/get-city-list.tsx
  client/hooks/api/location/get-country-list.tsx
  client/hooks/api/location/get-province-list.tsx
  client/hooks/api/post/get-post-list-by-user-uuid.tsx
  client/hooks/api/post/get-post.tsx
  client/hooks/api/post/search-post.tsx
  client/hooks/api/referral/search-referral.tsx
  client/hooks/api/user/get-user-count.tsx
  client/hooks/api/user/get-user-profile.tsx
  client/modules/post/common/post-status-options.ts
  client/modules/post/components/info-display/header.tsx
  client/modules/post/components/info-display/status.tsx
  client/modules/post/create/template.tsx
  client/modules/post/edit/template.tsx
  client/modules/post/history/components/cards/post-history.tsx
  client/modules/post/referee/template.tsx
  client/modules/post/referer/template.tsx
  client/modules/post/view/template.tsx
  client/modules/referral/components/dialog/contact.tsx
  client/modules/referral/referee/template.tsx
  client/modules/referral/referer/template.tsx
  client/types/api/request/contact/referral.ts
  client/types/api/request/post/search.ts
  client/types/api/request/post/update.ts
  client/types/api/response/referer-post.ts
  client/types/common/message-type.ts
  client/types/common/post-status.ts
  client/types/common/post.ts
  client/types/common/query-key-string.ts
  client/types/common/referral-type.ts
  client/types/nav.ts
  client/utils/common/api/index.tsx
Labels: refactoring

#260 Feature/create space for auth
  client/app/auth/forgot-password/page.tsx
  client/app/auth/sign-in/page.tsx
  client/app/auth/sign-up/page.tsx
  client/config/site.ts
  client/modules/auth/forgot-password/template.tsx
  client/modules/auth/sign-in/template.tsx
  client/modules/auth/sign-up/template.tsx
Labels: feature

#257 [Docs] Improvements and breaking down
  DEVELOPER.md
  README.md
  docs/BACKEND.md
  docs/CONTRIBUTING.md
  docs/FRONTEND.md
  docs/INTRODUCTION.md
Labels: documentation

#267 Feature/PWA installation instruction
  client/app/installation/page.tsx
  client/components/customized-ui/footer/nav.tsx
  client/components/ui/tabs.tsx
  client/config/site.ts
  client/modules/installation/components/tabs/installation.tsx
  client/modules/installation/data/index.ts
  client/modules/installation/data/page.ts
  client/modules/installation/data/tabs.ts
  client/package.json
  client/yarn.lock
Labels: feature, P1, Designer, Software Engineer

#255 search url using value instead of uuid
  client/components/customized-ui/pop-overs/search.tsx
  client/hooks/api/post/search-post.tsx
  client/hooks/api/referral/search-referral.tsx
  client/modules/contributors/data/contributors.ts
  client/modules/post/create/template.tsx
  client/modules/post/edit/template.tsx
  client/modules/post/referee/template.tsx
  client/modules/post/referer/template.tsx
  client/modules/profile/edit/template.tsx
  client/modules/referral/referee/template.tsx
  client/modules/referral/referer/template.tsx
  client/types/api/request/post/filter-meta.ts
  client/utils/common/api/index.tsx
  client/utils/common/sorting/post.ts
  client/utils/common/sorting/referer.ts
Labels: feature

#259 Feature/adding react testing library
  client/jest.config.js
  client/jest.config.mjs
  client/jest.setup.js
  client/modules/contributors/components/contribution-area-badge.test.tsx
  client/package.json
  client/tsconfig.json
  client/yarn.lock
  docs/CONTRIBUTING.md
  docs/Test.md
Labels: feature

#261 Feature/adding more husky config
  .commitlintrc.json
  .czrc
  .eslintrc.js
  .husky/commit-msg
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  CHANGELOG.md
  client/app/error.tsx
  client/app/loading.tsx
  client/app/post/create/page.tsx
  client/lib/exceptions.ts
  client/prettier.config.js
  docs/CONTRIBUTING.md
  package.json
  yarn.lock
Labels: feature

#270 CI/adding run client test ci
  .github/workflows/client-test.yml
  docs/CONTRIBUTING.md
Labels: feature

#268 Bugfix/husky run twice
  .husky/pre-commit
Labels: bug
