Repository Pjaijai/Referalah, pull requests merged in 2023-10, with the labels that each got.

#82 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#80 Feature/rename hook file name
  client/app/page.tsx
  client/app/profile/page.tsx
  client/components/customized-ui/cards/referral.tsx
  client/components/customized-ui/drop-down-menu/user.tsx
  client/components/customized-ui/pop-overs/search.tsx
  client/components/providers/auth.tsx
  client/components/site-header.tsx
  client/hooks/api/contact/referral.tsx
  client/hooks/api/contact/through-post.tsx
  client/hooks/api/industry/get-Industry-list.tsx
  client/hooks/api/location/get-city-list.tsx
  client/hooks/api/location/get-country-list.tsx
  client/hooks/api/location/get-province-list.tsx
  client/hooks/api/post/create-post.tsx
  client/hooks/api/post/search-post.tsx
  client/hooks/api/referral/search-referral.tsx
  client/hooks/api/user/get-user-count.tsx
  client/hooks/api/user/get-user-profile.tsx
  client/hooks/api/user/update-user-profile.tsx
  client/hooks/common/debounce.tsx
  client/hooks/common/options/city-options.tsx
  client/hooks/common/options/country-options.tsx
  client/hooks/common/options/industry-options.tsx
  client/hooks/common/options/province-pptions.tsx
  client/hooks/state/user/store.tsx
  client/modules/post/create/template.tsx
  client/modules/post/referee/template.tsx
  client/modules/post/referer/template.tsx
  client/modules/profile/edit/template.tsx
  client/modules/referral/components/dialog/contact.tsx
  client/modules/referral/referee/template.tsx
  client/modules/referral/referer/template.tsx
Labels: enhancement

#76 75 adding developer.md and update on readme
  DEVELOPER.md
  README.md
  client/README.md
Labels: documentation

#79 Feature/add GitHub link
  client/components/customized-ui/footer/nav.tsx
  client/components/icons.tsx
  client/components/site-header.tsx
  client/config/site.ts
  client/package.json
Labels: enhancement

#84 Hotfix/fix api not calling problem
  client/components/customized-ui/drop-down-menu/user.tsx
  client/components/providers/auth.tsx
  client/hooks/state/user/store.tsx
  client/utils/common/api/index.tsx
Labels: bug

#89 Feature/change 開post
  client/app/about/page.tsx
  client/components/customized-ui/drop-down-menu/user.tsx
  client/components/customized-ui/navigation-menu/base.tsx
  client/modules/post/create/template.tsx
  client/package.json
  client/utils/common/sorting/post.ts
  supabase/functions/contact-through-post/index.ts
Labels: enhancement

#92 Remove env
  supabase/.env.local
  supabase/.gitignore
Labels: bug

#93 Removing env file in supabase
  supabase/.env.local
  supabase/.gitignore
Labels: bug

#104 Feature/update backend setup on developer md
  .gitignore
  .vscode/settings.json
  DEVELOPER.md
Labels: feature

#103 add CORS to edge func depending on the staging env
  supabase/functions/_shared/cors.ts
Labels: feature

#106 Feature/ Change to error toast when failed to send contact request
  client/modules/referral/components/dialog/contact.tsx
Labels: feature

#109 add reply-to header to both contact email
  supabase/functions/contact-referral/index.ts
  supabase/functions/contact-through-post/index.ts
Labels: feature

#96 Feature/refactor search hook
  client/hooks/api/post/search-post.tsx
  client/hooks/api/referral/search-referral.tsx
  client/modules/post/referee/template.tsx
  client/modules/post/referer/template.tsx
  client/modules/referral/referee/template.tsx
  client/modules/referral/referer/template.tsx
Labels: feature

#121 [#120] set social media url to optional
  client/modules/post/create/template.tsx
  client/modules/profile/edit/template.tsx
Labels: bug

#122 Feature/make user profile page dynamic
  client/app/profile/[userUuid]/page.tsx
  client/components/customized-ui/drop-down-menu/user.tsx
  client/components/customized-ui/navigation-menu/base.tsx
  client/config/site.ts
  client/modules/profile/view/template.tsx
Labels: feature

#111 Feature/allow job title search
  client/components/customized-ui/buttons/reset.tsx
  client/components/icons.tsx
  client/hooks/api/post/search-post.tsx
  client/hooks/api/referral/search-referral.tsx
  client/modules/post/referee/template.tsx
  client/modules/post/referer/template.tsx
  client/modules/referral/referee/template.tsx
  client/modules/referral/referer/template.tsx
  client/utils/common/api/index.tsx
Labels: feature

#133 Should throw error after catching it
  client/utils/common/api/index.tsx
Labels: feature

#136 Feature/adding word limitation to create post page
  client/modules/post/create/template.tsx
Labels: feature

#138 Feature/config email testing on local environment
  DEVELOPER.md
  supabase/.env.template
  supabase/functions/_shared/cors.ts
  supabase/functions/contact-referral/index.ts
  supabase/functions/contact-through-post/index.ts
Labels: documentation

#124 Feature/adding type from supabase
  .github/workflows/production-update-types.yml
  .github/workflows/staging-update-types.yml
  client/hooks/state/user/store.tsx
  client/types/api/response/city.ts
  client/types/api/response/country.ts
  client/types/api/response/province.ts
  client/types/supabase.ts
  client/utils/common/api/index.tsx
  client/utils/services/supabase/config.ts
Labels: feature

#125 Feature/Adding initial data
  supabase/seed.sql
Labels: feature

#135 Feature/revamp card
  DEVELOPER.md
  client/app/layout.tsx
  client/app/profile/[userUuid]/page.tsx
  client/components/customized-ui/avatars/base.tsx
  client/components/customized-ui/cards/referral-post.tsx
  client/components/customized-ui/cards/referral.tsx
  client/components/customized-ui/info-display/company.tsx
  client/components/customized-ui/info-display/industry.tsx
  client/components/customized-ui/info-display/location.tsx
  client/components/customized-ui/info-display/post-header.tsx
  client/components/customized-ui/info-display/years-of-experience.tsx
  client/components/customized-ui/pop-overs/search.tsx
  client/components/customized-ui/skeletons /card-list.tsx
  client/components/customized-ui/skeletons /card.tsx
  client/components/customized-ui/tool/collapsible-text-wrapper.tsx
  client/components/customized-ui/tool/tooltip-wrapper.tsx
  client/components/icons.tsx
  client/components/layouts/search-page.tsx
  client/components/ui/card.tsx
  client/hooks/common/useTruncatedElement.tsx
  client/modules/post/referee/template.tsx
  client/modules/post/referer/template.tsx
  client/modules/referral/components/drop-down-menu/card.tsx
  client/modules/referral/referee/template.tsx
  client/modules/referral/referer/template.tsx
  client/tailwind.config.js
  client/types/api/response/referer-post.ts
  client/utils/common/api/index.tsx
  client/utils/common/helpers/format/date.ts
  client/utils/common/helpers/format/location.ts
  supabase/functions/_shared/cors.ts
  supabase/functions/contact-referral/index.ts
Labels: feature

#142 Refactor/fix all formart problem
  DEVELOPER.md
  client/app/about/page.tsx
  client/app/page.tsx
  client/app/post/referee/page.tsx
  client/app/post/referer/page.tsx
  client/app/profile/[userUuid]/page.tsx
  client/app/referee/page.tsx
  client/app/referer/page.tsx
  client/components/customized-ui/Infinite-scroll/base.tsx
  client/components/customized-ui/cards/referral-post.tsx
  client/components/customized-ui/cards/referral.tsx
  client/components/customized-ui/drop-down-menu/user.tsx
  client/components/customized-ui/form/check-box.tsx
  client/components/customized-ui/form/file.tsx
  client/components/customized-ui/form/input.tsx
  client/components/customized-ui/form/number.tsx
  client/components/customized-ui/form/select.tsx
  client/components/customized-ui/form/text-area.tsx
  client/components/customized-ui/info-display/post-header.tsx
  client/components/customized-ui/inputs/number.tsx
  client/components/customized-ui/navigation-menu/base.tsx
  client/components/customized-ui/selects/base.tsx
  client/components/customized-ui/tool/Link.tsx
  client/components/icons.tsx
  client/components/main-nav.tsx
  client/components/providers/api.tsx
  client/components/site-header.tsx
  client/components/theme-toggle.tsx
  client/components/ui/form.tsx
  client/components/ui/use-toast.ts
  client/modules/profile/edit/template.tsx
  client/utils/common/helpers/format/date.ts
Labels: refactoring

#144 Hotfix/fix post duplication
  client/components/customized-ui/cards/referral.tsx
  client/hooks/api/post/search-post.tsx
  client/hooks/api/referral/search-referral.tsx
  client/modules/post/referee/template.tsx
  client/modules/post/referer/template.tsx
  client/modules/referral/referee/template.tsx
  client/modules/referral/referer/template.tsx
  client/types/api/response/user.ts
  client/utils/common/api/index.tsx
Labels: bug

#145 Feature/adding tailwind plugin
  client/app/about/page.tsx
  client/app/auth/page.tsx
  client/app/page.tsx
  client/app/profile/[userUuid]/page.tsx
  client/components/customized-ui/Infinite-scroll/base.tsx
  client/components/customized-ui/avatars/base.tsx
  client/components/customized-ui/cards/referral-post.tsx
  client/components/customized-ui/cards/referral.tsx
  client/components/customized-ui/drop-down-menu/user.tsx
  client/components/customized-ui/info-display/company.tsx
  client/components/customized-ui/info-display/industry.tsx
  client/components/customized-ui/info-display/location.tsx
  client/components/customized-ui/info-display/post-header.tsx
  client/components/customized-ui/info-display/years-of-experience.tsx
  client/components/customized-ui/inputs/number.tsx
  client/components/customized-ui/links/highlighted.tsx
  client/components/customized-ui/navigation-menu/base.tsx
  client/components/customized-ui/skeletons /card-list.tsx
  client/components/customized-ui/skeletons /card.tsx
  client/components/customized-ui/tool/collapsible-text-wrapper.tsx
  client/components/layouts/search-page.tsx
  client/components/site-header.tsx
  client/components/ui/form.tsx
  client/database.types.ts
  client/modules/auth/template.tsx
  client/modules/post/create/template.tsx
  client/modules/post/referee/template.tsx
  client/modules/post/referer/template.tsx
  client/modules/profile/edit/template.tsx
  client/modules/profile/view/template.tsx
  client/modules/referral/referee/template.tsx
  client/modules/referral/referer/template.tsx
  client/package.json
  client/prettier.config.js
  client/types/supabase.ts
  client/yarn.lock
Labels: feature, refactoring

#160 Bugfix/Card UI
  client/components/customized-ui/cards/referral-post.tsx
  client/components/customized-ui/cards/referral.tsx
  client/components/customized-ui/info-display/company.tsx
  client/components/customized-ui/info-display/industry.tsx
  client/components/customized-ui/info-display/location.tsx
  client/components/customized-ui/info-display/post-header.tsx
  client/components/customized-ui/info-display/years-of-experience.tsx
  client/hooks/common/useViewport.tsx
Labels: bug

#156 Bugfix/fix contact dialog text
  client/modules/referral/components/dialog/contact.tsx
Labels: bug

#163 BugFix/Fix button in mobile view in main page
  client/app/page.tsx
Labels: bug

#162 BugFix/Add word break
  client/components/customized-ui/cards/referral-post.tsx
  client/components/customized-ui/cards/referral.tsx
Labels: bug

#146 Doc/adding local db dev guidelines
  DEVELOPER.md
Labels: documentation

#173 add frontend setup docs
  DEVELOPER.md
Labels: documentation

#172 Refactor/fixing site config and using common layout
  client/app/auth/page.tsx
  client/app/post/create/page.tsx
  client/app/post/referee/page.tsx
  client/app/post/referer/page.tsx
  client/app/profile/[userUuid]/page.tsx
  client/app/referee/page.tsx
  client/app/referer/page.tsx
  client/components/layouts/common.tsx
  client/components/layouts/search-page.tsx
  client/config/site.ts
  client/modules/post/create/template.tsx
Labels: refactoring

#174 Feature/contributors page
  client/app/contributors/page.tsx
  client/app/page.tsx
  client/components/customized-ui/footer/nav.tsx
  client/components/icons.tsx
  client/config/site.ts
  client/modules/contributors/components/contribution-area-badge.tsx
  client/modules/contributors/components/contributor-card.tsx
  client/modules/contributors/data/contributors.ts
  client/modules/contributors/template.tsx
  client/modules/contributors/types/ contributed-area.ts
  client/modules/contributors/types/contributor.ts
  client/modules/contributors/uilts/get-contribution-area-text.ts
Labels: feature

#181 Feature/Adding reminder message to contact dialog
  client/modules/referral/components/dialog/contact.tsx
Labels: feature

#180 Feature/Adding contributor
  client/modules/contributors/data/contributors.ts
Labels: feature

#171 Refactor/refactor use search post and api
  client/hooks/api/post/search-post.tsx
  client/types/api/request/post/search.ts
  client/utils/common/api/index.tsx
Labels: refactoring

#183 Feature/post detail page
  client/app/post/referee/[uuid]/page.tsx
  client/app/post/referer/[uuid]/page.tsx
  client/components/customized-ui/cards/profile.tsx
  client/components/customized-ui/cards/referral-post.tsx
  client/components/customized-ui/cards/referral.tsx
  client/components/customized-ui/info-display/created-at.tsx
  client/components/customized-ui/info-display/post-details-info.tsx
  client/components/customized-ui/info-display/post-header.tsx
  client/components/customized-ui/info-display/post-status.tsx
  client/components/customized-ui/tool/collapsible-text-wrapper.tsx
  client/components/icons.tsx
  client/components/layouts/page-status.tsx
  client/components/ui/badge.tsx
  client/hooks/api/post/get-post.tsx
  client/modules/post/view/template.tsx
  client/types/api/response/referer-post.ts
  client/types/common/post-status.ts
  client/types/common/query-key-string.ts
  client/utils/common/api/index.tsx
  client/utils/common/mappers/translation/referral-type.ts
  supabase/migrations/20231030011251_create_post_status_enum.sql
Labels: feature

#185 Feature/Simplify referral post card
  client/components/customized-ui/cards/referral-post.tsx
  client/components/customized-ui/info-display/post-header.tsx
Labels: feature

#187 Bugfix/fix auth page layout problem
  client/app/auth/page.tsx
  client/modules/auth/template.tsx
Labels: bug

#186 Feature/remove referee post page
  client/app/post/referee/[uuid]/page.tsx
  client/app/post/referee/page.tsx
  client/app/post/referer/[uuid]/page.tsx
  client/components/customized-ui/cards/profile.tsx
  client/components/customized-ui/cards/referral-post.tsx
  client/components/customized-ui/drop-down-menu/user.tsx
  client/components/customized-ui/info-display/created-at.tsx
  client/components/customized-ui/navigation-menu/base.tsx
  client/config/site.ts
  client/modules/post/components/info-display/details-info.tsx
  client/modules/post/components/info-display/header.tsx
  client/modules/post/components/info-display/status.tsx
  client/modules/post/create/template.tsx
  client/modules/post/referee/template.tsx
  client/modules/post/view/template.tsx
  client/utils/common/mappers/translation/referral-type.ts
Labels: feature
